### ISSUE TITLE
Setup NGP demonstration of an actuator line/disk simulation for ECP FY20-Q4 milestone

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#632]
- [x] Setup nightly regression test of fixed wing actuator line (#627)
- [x] Ensure all GPU builds include OpenFAST integration (on SNL testbeds and ORNL Summit)
- [ ] Convert NREL-5MW actuator line simulation to run on GPU
- [ ] Create the demonstration problem setup that will be used for Q4 milestone
